name: tmq
description: A new Flutter project.


publish_to: 'none'
version: 4.1.4+12

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  firebase_core: ^2.1.1
  another_flushbar: ^1.10.28
  package_info_plus: ^1.0.0
  url_launcher: ^6.1.6
  cloud_firestore: ^4.0.3
  sqflite: ^2.2.0+2 
  fluttertoast: ^8.0.9
  cached_network_image: ^3.2.0
  google_fonts: ^2.1.1
  carousel_slider: ^4.0.0
  delayed_display: ^2.0.0
  shimmer: ^2.0.0
  firebase_messaging: ^14.0.3
  flutter_local_notifications: ^9.4.0
  animated_splash_screen: ^1.2.0
  flutter_spinkit: ^5.1.0
  loading_animation_widget: ^1.1.0+3
  image_gallery_saver: ^1.7.1
  dio: ^4.0.6
  permission_handler: ^10.2.0
  device_preview: ^1.0.0
  flutter_cache_manager: ^3.3.0
  # new_version_plus: ^0.0.3
  connectivity_plus: ^2.3.0
  flutter_lints: ^1.0.4
  new_version: ^0.3.1
  flutter_native_splash: ^2.1.5
  update_notification: ^1.0.1
  flutter_native_image: ^0.0.6
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/



flutter_native_splash:
    color: "#fafafa"
    image: assets/splash.png
    ios_content_mode: center
    android_gravity: center
    android: true
    anroid12: true
    ios: true
    web: false
    

flutter_localization:
    sdk: flutter

